矩阵的LU分解
1. 分解之后，矩阵形式并不等于原矩阵，但是det一定相等，原方程组和后来的是等价的
2. 当A的前n阶主子式都不为0时，才有LU分解
3. 这个LU分解叫做行尺度的LU分解，不是普通的LU分解
4. 普通的LU分解可以理解为秩1矩阵之和

In [ ]:
import numpy as np
from scipy.linalg import lu

B = np.array([[3, -7, -2, 2], 
              [-3, 5, 1, 0], 
              [6, -4, 0, -5], 
              [-9, 5, -5, 12]])

A = np.array([[2, 3, -6], 
              [1, -6, 8], 
              [3, -2, 1]])

P, L, U = lu(A)
F = np.dot(L, U)
print(P)
print(L)
print(U)
print(f"A's det is {np.linalg.det(A)}")
print(np.linalg.det(P @ A) == np.linalg.det(F))
print(P @ A == F)

马尔科夫链
1. X--状态向量
2. P--随机矩阵，每列都是概率向量，和为1
3. 实际上是全概率定理

In [ ]:
import numpy as np
X_one = np.array([0.85, 0.10, 0.05, 0.00]).reshape(4, 1)
P = np.array([[0.90, 0.00, 0.00, 0.00], 
              [0.07, 0.93, 0.00, 0.00], 
              [0.02, 0.05, 0.85, 0.00], 
              [0.01, 0.02, 0.15, 1.00]])
X_two = P @ X_one
print(f"经过一年后的状态向量"
      f" {X_two}")

计算机计算/存储数字的问题(when repeating an operation many times, since each operation could multiply the error)


In [ ]:
def f(x):
    if x <= 1/2:
        return 2 * x
    if x > 1/2:
        return 2*x - 1


x = 1/10
for i in range(80):
    print(x)
    x = f(x)
# 理应是一个循环(计算前10次的结果)

1. suppress: 当设置为 True 时，可以抑制数组中的科学计数法表示
2. precision: 指定浮点数的打印精度（小数点后的位数）。默认值为6
3. BLAS and LAPACK,numpy执行线性代数幕后的package

In [ ]:
import scipy.linalg as la
import numpy as np
A = np.array([[1., 1000], [0, 1]])
B = np.array([[1, 1000], [0.001, 1]])
np.set_printoptions(suppress=True, precision=4)
wA, vrA = la.eig(A)
wB, vrB = la.eig(B)
print(wA)
print(wB)

影响计算速度的因素
1. Computational complexity
2. Vectorization
3. Matrix Computation Packages: BLAS and LAPACK
4. Locality
5. Scaling to multiple cores and nodes
6. Scalability / parallelization
7. Sparse vs Dense

1. 对角占优矩阵（Diagonally Dominant Matrix）是一种特殊类型的矩阵，,特点是每一行的对角线元素的绝对值都大于或等于该行其他元素绝对值的和
2. 非奇异，有LU分解
3. 行尺度LU分解不用选择主元，是自然顺序

Topic Modeling with NMF and SVD
1. 未考虑词的顺序和句的结构，是一个词袋方法
2. 分解为3个矩阵
3. 类内相似，类间不相似
4. SVD也可以看作秩1矩阵的组合

In [ ]:
import numpy as np
from sklearn import decomposition
from scipy import linalg
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_20newsgroups
%matplotlib inline
np.set_printoptions(suppress=True)

categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space']
remove = ('headers', 'footers', 'quotes')
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=remove)
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=remove)
print(newsgroups_train.shape)
print(newsgroups_test.shape)
print("\n".join(newsgroups_train.data[:3]))

矩阵的CSR格式，存储稀疏矩阵
1. 数据数组（Data）：存储非零元素的值
2. 行指针数组（Row Pointers） 第一个元素总是0，之后的元素是每一行元素的个数的累计和
3. 列索引数组（Column Indices）


In [2]:
# todo 创建一个稀疏矩阵
import numpy as np
from scipy.sparse import csr_matrix
data = np.array([1, 2, 3, 5, 8, 4])
indptr = np.array([0, 2, 4, 6])
indices = np.array([0, 1, 1, 2, 0, 2])
A_csr = csr_matrix((data, indices, indptr), shape=(3, 3))
print(A_csr)

  (0, 0)	1
  (0, 1)	2
  (1, 1)	3
  (1, 2)	5
  (2, 0)	8
  (2, 2)	4


秩1矩阵
由一个列向量和一个行向量的乘法得到

In [ ]:
import numpy as np
a = np.array([1, 2, 5]).reshape(3, 1)
b = np.array([4, 2, 1]).reshape(1, 3)
# todo 计算矩阵的秩
print(np.linalg.matrix_rank(a @ b))

投影矩阵
1. P**2 == P， 意味着对任意向量 𝑣，当 𝑣被𝑃作用一次后，再作用一次 P 不会改变结果。也就是说，P 的作用是将向量“投影”到某个子空间上--幂等性
2. 若对称，则叫做正交投影矩阵
3. 投影矩阵的特征值只能是 0 或 1。特征值为 1 的特征向量属于投影子空间，而特征值为 0 的特征向量属于投影子空间的正交补(零空间和行空间相互垂直，秩定理)(核)
4. 

QR分解，正交化过程·

In [5]:
import numpy as np

# 定义一个矩阵 A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

# 使用 numpy.linalg.qr 进行 QR 分解
Q, R = np.linalg.qr(A)

# 打印结果
print("矩阵 A:")
print(A)
print("正交矩阵 Q:")
print(Q)
print("上三角矩阵 R:")
print(R)
print(np.allclose(Q @ Q.T, np.eye(Q.shape[0])))

矩阵 A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
正交矩阵 Q:
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
上三角矩阵 R:
[[ -8.1240384   -9.6011363  -11.93987462]
 [  0.           0.90453403   1.50755672]
 [  0.           0.           0.40824829]]
True


对称矩阵的对角化
1. 特征向量是正交矩阵，已经单位化

In [12]:
import numpy as np

# 定义一个对称矩阵
A = np.array([[2, 1],
              [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"这是特征值：{eigenvalues}")
print("特征向量:")
print(eigenvectors)
print(np.allclose(eigenvectors@eigenvectors.T, np.eye(eigenvectors.shape[0])))
# 构造对角矩阵
D = np.diag(eigenvalues)
print(f"对角阵{D}")
print(f"验证{np.allclose(A, eigenvectors@ D @np.linalg.inv(eigenvectors))}")
print(f"验证{np.allclose(A, eigenvectors@ D @ eigenvectors.T)}")

这是特征值：[1.38196601 3.61803399]
特征向量:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
True
对角阵[[1.38196601 0.        ]
 [0.         3.61803399]]
验证True
验证True
